"""user model

Revision ID: d19b7fb8bd96
Revises:
Create Date: 2023-12-24 09:58:07.443552

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd19b7fb8bd96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('telegram_id', sa.BIGINT(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('language_code', sa.String(), nullable=False),
        sa.Column('first_bot_launch', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('telegram_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
