"""application model

Revision ID: e7b9cf718adc
Revises: d19b7fb8bd96
Create Date: 2023-12-25 12:25:25.037052

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e7b9cf718adc'
down_revision = 'd19b7fb8bd96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'applications',
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('job_position', sa.String(), nullable=False),
        sa.Column('vacancy_url', sa.String(), nullable=True),
        sa.Column('company_name', sa.String(), nullable=False),
        sa.Column('salary', sa.String(), nullable=True),
        sa.Column('job_description', sa.String(), nullable=True),
        sa.Column('contacts', sa.String(), nullable=True),
        sa.Column('applied_date', sa.Date(), nullable=False),
        sa.Column('follow_up_date', sa.Date(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'applied',
                'interviewing',
                'negotiating',
                'accepted',
                'declined',
                'rejected',
                'archived', name='applicationstatus',
            ),
            nullable=False,
        ),
        sa.Column('user_id', sa.BIGINT(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
